### ISSUE TITLE
Distributed Tracing Not Working

### ISSUE THREAD

**Issue by itajenglish** [newrelic/newrelic-react-native-agent#102]
## Description
Distributed tracing between React Native Agent and backend agents doesn't seem to be working. In the New Relic UI, none of the internal services show up in the trace UI or service map

## Steps to Reproduce

Make API calls to backend services instrumented by New Relic Infrastructure and APM agents.

## Expected Behavior

Distributed traces to backend services show up in the New Relic mobile service map and trace UI.

## Your Environment

New Relic React Native Agent SDK Version: 1.2.0
React Native Version: 0.71.7
Expo SDK Version: 48.0.15
OS: iOS
OS Version: 16.2
Device: iPhone 13 Pro

## Additional context
<img width="1724" alt="Screenshot 2023-05-26 at 8 05 34 PM" src="https://github.com/newrelic/newrelic-react-native-agent/assets/889564/3ce5ee0d-5a45-4cfb-96e9-e0530ce65cf0">

**Comment by NicholasGWK** [comment]
Hey @itajenglish , what ended up being the cause here? Wondering if it's related to some issues I'm having currently :P

**Comment by itajenglish** [comment]
Hey @NicholasGWK, I believe it started to show on it's own after a while. Are you running your backend on Kubernetes?
