### ISSUE TITLE
Android Build Failing With React Native Gesture Handler And New Relic

### ISSUE THREAD

**Issue by itajenglish** [newrelic/newrelic-react-native-agent#105]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

New Relic seems to be causing issues with React Native Gesture Handler. When New Relic is uninstalled our Android App is building. I have a demo repo [here](https://github.com/itajenglish/rn-gesture-handler-error) showcasing the problem. Run `yarn run android` to see the failing build. Uninstall New Relic and observe the build succeed.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

1. Install New Relic React Native Agent
2. Install React Native Gesture Handler

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

- Android app builds

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[Link](https://github.com/software-mansion/react-native-gesture-handler/issues/2503) to issue submitted to [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) repo. This includes the failing build log 

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

```
    "@config-plugins/react-native-branch": "^5.0.0",
    "@devcycle/devcycle-react-native-sdk": "^1.2.6",
    "@expo-google-fonts/lato": "^0.2.2",
    "@expo/vector-icons": "^13.0.0",
    "@hookform/resolvers": "^2.9.10",
    "@intercom/intercom-react-native": "^4.0.1",
    "@listedb/common-utils": "^1.13.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-firebase/app": "^16.5.0",
    "@react-native-firebase/messaging": "^16.5.0",
    "@react-native-seoul/masonry-list": "^1.4.1",
    "@react-navigation/elements": "1.3.17",
    "@react-navigation/material-top-tabs": "6.6.2",
    "@react-navigation/native": "6.1.6",
    "@react-navigation/native-stack": "6.9.12",
    "@segment/analytics-react-native": "^2.14.0",
    "@segment/sovran-react-native": "^1.0.3",
    "@stytch/react-native": "^0.7.1",
    "@stytch/react-native-expo": "^0.8.2",
    "@svanboxel/visibility-sensor-react-native": "^1.0.2",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^1.2.0",
    "burnt": "^0.10.0",
    "config-plugin-react-native-intercom": "^1.10.1",
    "expo": "~48.0.18",
    "expo-app-loading": "~2.1.1",
    "expo-asset": "~8.9.1",
    "expo-av": "~13.2.1",
    "expo-build-properties": "~0.6.0",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linking": "~4.0.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.16.4",
    "expo-web-browser": "~12.1.1",
    "getstream": "^8.1.0",
    "humanize-duration": "^3.27.3",
    "lodash": "^4.17.21",
    "newrelic-react-native-agent": "^1.2.0",
    "patch-package": "^6.5.0",
    "phone-formatter": "^0.0.2",
    "postinstall-postinstall": "^2.1.0",
    "prop-types": "^15.8.1",
    "query-string": "^7.1.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.39.6",
    "react-native": "0.71.8",
    "react-native-actions-sheet": "0.8.29",
    "react-native-activity-feed": "1.1.0",
    "react-native-animated-nav-tab-bar": "^3.1.8",
    "react-native-branch": "^5.4.0",
    "react-native-calendars": "^1.1294.0",
    "react-native-device-info": "^10.6.0",
    "react-native-dotenv": "^3.4.2",
    "react-native-drop-shadow": "^0.0.6",
    "react-native-dropdown-picker": "^5.4.3",
    "react-native-dropdownalert": "^4.5.1",
    "react-native-elements": "^3.4.2",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-get-random-values": "~1.8.0",
    "react-native-gleapsdk": "^8.2.4",
    "react-native-image-crop-picker": "^0.38.1",
    "react-native-image-viewing": "^0.2.2",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-internet-connection-alert": "^0.1.9",
    "react-native-keychain": "^8.1.1",
    "react-native-neat-date-picker": "1.4.7",
    "react-native-pager-view": "6.1.2",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-tab-view": "^3.3.0",
    "react-native-timeago": "^0.5.0",
    "react-native-ui-lib": "^6.24.0",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "~0.18.7",
    "react-redux": "^8.0.5",
    "redux": "^4.2.0",
    "redux-act": "^1.8.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-thunk": "^2.4.2",
    "styled-components": "^5.3.6",
    "yup": "^0.32.11"
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by ndesai-newrelic** [comment]
@itajenglish the same is happened without newrelic npm package too.they have same issue for their other package in the past. https://github.com/software-mansion/react-native-reanimated/issues/2711

**Comment by itajenglish** [comment]
@ndesai-newrelic Do you have any ideas or suggestions on the next step with this as it only seems to happen when we have the New Relic agent installed? Is this something that can be fixed on the New Relic side? This issue is preventing us from launching our Android app hurting our business. I would appreciate any guidance on this. Thank you!

**Comment by ndesai-newrelic** [comment]
@itajenglish  I discovered that our New Relic package and the Expo Dev Client are not compatible, which is causing this issue.

The Expo Dev Client is a debugging tool. If you wish to use it in your development environment, please disable the New Relic agent.                                        You can build the app using the command npx react-native run-android --variant=release, which will not cause a build failure even if you have both the Expo Dev Client and New Relic in your app.

**Comment by ndesai-newrelic** [comment]
@itajenglish there is no ETA but we will try to fix this ASAP.

**Comment by itajenglish** [comment]
> @itajenglish there is no ETA but we will try to fix this ASAP.

@ndesai-newrelic Thanks for the response. I'll keep an eye out for any updates.

**Comment by ndesai-newrelic** [comment]
@itajenglish I have successfully built the project using the latest React Native agent with this configuration.
<img width="388" alt="Screenshot 2023-07-21 at 2 41 40 PM" src="https://github.com/newrelic/newrelic-react-native-agent/assets/89222514/c091ea53-6949-4c2b-b26d-d80db9bc0e30">

**Comment by itajenglish** [comment]
Hi @ndesai-newrelic Thank you! The app is now successfully built with the latest New Relic SDK 🎉
