### ISSUE TITLE
Newrelic agent has conflicts with Firebase Dynamic Link SDK on iOS

### ISSUE THREAD

**Issue by wayson** [newrelic/newrelic-react-native-agent#109]
## Description

Our app has integrated with react native Firebase and Newrelic react native agent. Both of them work perfectly until we upgraded the RN newrelic agent from 0.0.8 to 1.2.0. 

According to firebase ios sdk github error ticket, it seems the RN Newrelic agent has conflicts with Firebase SDK(Dynamic Links) on iOS. [https://github.com/firebase/firebase-ios-sdk/issues/7318#issuecomment-765055857](https://github.com/firebase/firebase-ios-sdk/issues/7318#issuecomment-765055857)

## Steps to Reproduce

Use Newrelic RN agent to 1.2.0 and use RN Firebase sdk at the same time in release(production). 

## Expected Behavior

No error should be reported in firebase

## Relevant Logs / Console output

Firebase Crashlytic output:

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000a916bd880

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x4174 objc_release + 16
1  libobjc.A.dylib                0x4174 objc_release_x0 + 16
2  OUR_APP_NAME                   0x66adc __55-[FIRDLJavaScriptExecutor webView:didFinishNavigation:]_block_invoke_2 + 140 (FIRDLJavaScriptExecutor.m:140)
3  WebKit                         0x5cedfc <redacted> + 332
4  WebKit                         0x5cea24 <redacted> + 84
5  WebKit                         0x505150 <redacted> + 64
6  WebKit                         0x9e0220 <redacted> + 712
7  WebKit                         0x9e0584 <redacted> + 284
8  JavaScriptCore                 0x54004 WTF::RunLoop::performWork() + 200
9  JavaScriptCore                 0x54ed0 WTF::RunLoop::performWork(void*) + 36
10 CoreFoundation                 0xd3128 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
11 CoreFoundation                 0xdf7b4 __CFRunLoopDoSource0 + 176
12 CoreFoundation                 0x64648 __CFRunLoopDoSources0 + 340
13 CoreFoundation                 0x7a0d4 __CFRunLoopRun + 828
14 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
15 GraphicsServices               0x135c GSEventRunModal + 164
16 UIKitCore                      0x39d6e8 -[UIApplication _run] + 888
17 UIKitCore                      0x39d34c UIApplicationMain + 340
18 OUR_APP_NAME                   0x486c main + 8 (main.m:8)
19 ???                            0x1a94e2dec (Missing)

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/waysonlin/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 31, 33, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Additional context

[https://github.com/firebase/firebase-ios-sdk/issues/7318#issuecomment-765055857](https://github.com/firebase/firebase-ios-sdk/issues/7318#issuecomment-765055857)

**Comment by ndesai-newrelic** [comment]
@wayson can you start NewRelic agent first before you start Firebase agent? this will help you to resolve this issue.

**Comment by wayson** [comment]
@ndesai-newrelic How can I do that in React Native application?

I've done that in root index.js like this:

`
/**
 * @format
 */

import {AppRegistry} from 'react-native';
// import App from './App';
import App from './src/app';
import {name as appName} from './app.json';
import NewRelic from 'newrelic-react-native-agent';
import DeviceInfo from 'react-native-device-info';

const agentConfiguration = {
  //Android Specific
  // Optional:Enable or disable collection of event data.
  analyticsEventEnabled: true,

  // Optional:Enable or disable crash reporting.
  crashReportingEnabled: true,

  // Optional:Enable or disable interaction tracing. Trace instrumentation still occurs, but no traces are harvested. This will disable default and custom interactions.
  interactionTracingEnabled: true,

  // Optional:Enable or disable reporting successful HTTP requests to the MobileRequest event type.
  networkRequestEnabled: true,

  // Optional:Enable or disable reporting network and HTTP request errors to the MobileRequestError event type.
  networkErrorRequestEnabled: true,

  // Optional:Enable or disable capture of HTTP response bodies for HTTP error traces, and MobileRequestError events.
  httpRequestBodyCaptureEnabled: true,

  //Android Specific
  // Optional: Enable or disable agent logging.
  loggingEnabled: true,

  //iOS Specific
  // Optional:Enable/Disable automatic instrumentation of WebViews
  webViewInstrumentation: true,
};

NewRelic.startAgent('NR_AGENT_KEY', agentConfiguration);

NewRelic.setJSAppVersion(DeviceInfo.getVersion());
AppRegistry.registerComponent(appName, () => App);
`

But it doesn't mean we can have nr agent run in the first place. According to [https://rnfirebase.io/#configure-firebase-with-ios-credentials](https://rnfirebase.io/#configure-firebase-with-ios-credentials) , firebase is run in native way and it comes in the first place. 

Do you know how we make NR agent run before firebase in native ios code?

**Comment by ndesai-newrelic** [comment]
@wayson  For now, there is a temporary workaround to address this issue. Please comment out the following line in the NRMModularAgent.m package:

```objc
[NewRelic startWithApplicationToken: appKey];
```

Then, start the agent from your AppDelegate file using:

```objc
[NewRelic startWithApplicationToken: appKey];
```

Make sure to replace `appKey` with your specific application key. I understand this is a short-term solution until we permanently fix the issue.

**Comment by abgaryanharutyun** [comment]
> @wayson For now, there is a temporary workaround to address this issue. Please comment out the following line in the NRMModularAgent.m package:
> 
> ```objc
> [NewRelic startWithApplicationToken: appKey];
> ```
> 
> Then, start the agent from your AppDelegate file using:
> 
> ```objc
> [NewRelic startWithApplicationToken: appKey];
> ```
> 
> Make sure to replace `appKey` with your specific application key. I understand this is a short-term solution until we permanently fix the issue.

Hey @ndesai-newrelic this short term solution works for me i have added patch for this changes 

diff --git a/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m b/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m
index 1d0c12d..5895705 100644
--- a/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m
+++ b/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m
@@ -102,7 +102,7 @@ - (dispatch_queue_t)methodQueue{
     [NewRelic setPlatformVersion:agentVersion];
     
     if (useDefaultCollectorAddress && useDefaultCrashCollectorAddress) {
-        [NewRelic startWithApplicationToken: appKey];
+//         [NewRelic startWithApplicationToken: appKey];
     } else {
         NSString* collectorAddress = useDefaultCollectorAddress ? @"mobile-collector.newrelic.com" : [agentConfig objectForKey:@"collectorAddress"];
         NSString* crashCollectorAddress = useDefaultCrashCollectorAddress ? @"mobile-crash.newrelic.com" : [agentConfig objectForKey:@"crashCollectorAddress"];

**Comment by wayson** [comment]
@ndesai-newrelic It works for me as a temporary solution. Thanks for your help.

**Comment by wayson** [comment]
@Vitor-Vilela Yes. The firebase monitoring was back to normal with this workaround.
