### ISSUE TITLE
Got "New Relic detected an unrecognized selector, 'swizzled_viewDidLayoutSubviews', sent to 'UIViewController'" on iOS with react-native-reanimated

### ISSUE THREAD

**Issue by saladestomateoignon** [newrelic/newrelic-react-native-agent#111]
Hello,
I am having an issue using newRelic on a react-native app with react-native-reanimated (New Relic detected an unrecognized selector, 'swizzled_viewDidLayoutSubviews', sent to 'UIViewController'. It's possible _cmd was renamed by an unsafe method_exchangeImplementations()).

I tried to integrate new-relic-react-native-agent into my react-native project. I followed all the steps here: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/.  

Everything seems to be setup correctly and package.json looks like this:
```
"newrelic-react-native-agent": "^1.2.1",
"react-native-reanimated": "^3.3.0",
"react": "18.2.0",
"react-native": "0.71.11",
```

When I run the app by using yarn ios, the app starts correctly and I can see these two logs appearing:
```
[NRMA] React Native agent started.
[NRMA] New Relic React Native agent version 1.2.1
```

However, as soon as I start displaying a component importing react-native-reanimated, the app crashes on iOS.
Into my new relic project, I have the below info regarding the crash:
```
JSEngine: Hermes

React Native Version: 0.71.11

ReactNativeAgentVersion: 1.2.1

architecture: arm64e

crashException: NRInvalidArgumentException

crashMessage: New Relic detected an unrecognized selector, 'swizzled_viewDidLayoutSubviews', sent to 'UIViewController'. It's possible _cmd was renamed by an unsafe method_exchangeImplementations().

lastInteraction: Display RNScreensNavigationController

networkStatus: WiFi

newRelicVersion: 7.4.5

osBuild: 22F66

osMajorVersion: 16

osName: iOS

osVersion: 16.4

parentProcess: launchd_sim

platform: ReactNative

platformVersion: 1.2.1
```

On any other component without react-native-reanimated import, I don't have the crash.
Have you ever had this issue before?

Thanks.

**Comment by ndesai-newrelic** [comment]
@saladestomateoignon can you share your agent configuration?

**Comment by ndesai-newrelic** [comment]
@saladestomateoignon Could you modify the agent configuration and set interactionTracingEnabled to false, then verify if the issue persists?

**Comment by ndesai-newrelic** [comment]
@saladestomateoignon are you using firebase? it look like you are using firebase

**Comment by ndesai-newrelic** [comment]
@saladestomateoignon both are trying to do swizzling and the default interaction tracing automatically instruments UIKit view controller functions, such as viewWillLayoutSubviews. This issue usually occurs when another library in the stack is also swizzling UIKit view controller methods, resulting in conflicts.
