### ISSUE TITLE
Expo 49 and @expo/config-plugins

### ISSUE THREAD

**Issue by StaffLyft** [newrelic/newrelic-react-native-agent#112]
With Expo 49 it is @expo/config-plugins@~7.2.2
Current dependency is @expo/config-plugins@6.0.2 which produce an issue message when run npx expo-doctor command in project

**Comment by ndesai-newrelic** [comment]
@StaffLyft The issue will be resolved in the upcoming release. Thank you for bringing it to our attention.

**Comment by ndesai-newrelic** [comment]
@StaffLyft it is fixed in latest release.
