### ISSUE TITLE
Pod install fails with error from AndroidManifest.xml

### ISSUE THREAD

**Issue by JoL0712** [newrelic/newrelic-react-native-agent#118]
## Description

We are developing an app in react-native but currently we are starting with prioritizing iOS development.
After installing newrelic-react-native-agent and running pod install we get the following error:
`error Failed to build the app: No package name found. Found errors in /node_modules/newrelic-react-native-agent/android/src/main/AndroidManifest.xml.`

## Steps to Reproduce

In a react-native app:
1. npm i newrelic-react-native-agent
2. cd ios && pod install

## Expected Behavior

We expect the pod install to succeed.

The current workaround we have is to modify `node_modules/newrelic-react-native-agent/android/src/main/AndroidManifest.xml` and add a package name:
```

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.newrelic">

</manifest>
  
```

**Comment by ndesai-newrelic** [comment]
@JoL0712 Which version of react native are you using?

**Comment by ndesai-newrelic** [comment]
@JoL0712 We have updated this file to accommodate changes in Android Gradle Plugin 8 and React Native 0.72.0. I will further test these modifications on my end, and if needed, we will revert the changes. However, I have not been able to reproduce the issue for iOS while running `pod install`.

**Comment by JoL0712** [comment]
Okay got it, we'll keep looking further for possible reasons.
Also as a reference here is our Podfile and we are using COCOAPODS: 1.12.1:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'Package' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    # :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'PackageTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
end
```

**Comment by ndesai-newrelic** [comment]
@JoL0712 This issue has been observed specifically with React Native version 0.70.x, and it appears that other libraries are experiencing similar problems. To address this issue, please try updating your React Native version and then test to see if the problem persists. Updating to a newer version may resolve compatibility or bug-related issues, leading to improved library performance.

**Comment by JoL0712** [comment]
Yeah bumping to 0.70.x fixes the issue. Thank you
