### ISSUE TITLE
No support for Gradle 8

### ISSUE THREAD

**Issue by spsaucier** [newrelic/newrelic-react-native-agent#122]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
Upgrading to React Native 0.72 updates Gradle to version 8.0.1.

`new-relic-react-native-agent` does not work with Gradle version 8. There appear to be workarounds for native Android apps, but this package does not include them: https://docs.google.com/document/d/1lVf40qbB0J1v47K1lNNYHuOsCmLJqztEE2S_SZcFl2Q/edit

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
Create new React Native app & try to install this package and build for Android.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
App builds & installs

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:transformClassesWithNewrelicTransformForDebug'.
   > Cannot use @TaskAction annotation on method IncrementalTransformTask.transform() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

```
System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 102.03 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.14.2
    path: ~/.nvm/versions/node/v18.14.2/bin/node
  Yarn:
    version: 1.22.17
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.14.2/bin/npm
  Watchman:
    version: 2023.07.24.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/stephensaucier/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: "18.2"
  react-native:
    installed: 0.72.4
    wanted: ^0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by ndesai-newrelic** [comment]
@spsaucier which version react native version are you using? please check our release 1.3.0 where we added support for Gradle 8.0. https://docs.newrelic.com/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-130/

**Comment by sebasg0** [comment]
Hi @ndesai-newrelic, I'm migrating to latest react native version 0.72.4 but getting above issue with latest new relic agent version which is 1.3.1 any other approach you will suggest?

**Comment by spsaucier** [comment]
I was using `newrelic-react-native-agent@1.3.1` when I encountered this issue.

**Comment by spsaucier** [comment]
Thanks @sebasg0, that did resolve it!
