### ISSUE TITLE
compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by HilSny** [newrelic/newrelic-react-native-agent#133]
## Description

Android will fail to compile 

## Steps to Reproduce

- try and build android on a react native app with latest installed 

## Expected Behavior

I expect the app to build

## Relevant Logs / Console output

[NOTE]: # 
```
> Configure project :newrelic-react-native-agent
:newrelic-react-native-agent package.json found at /Users/hillary.snyder/Documents/Projects/movespring/ms-mobile/node_modules/newrelic-react-native-agent/package.json
:newrelic-react-native-agent:newrelic.android using default value: 7.0.0
:newrelic-react-native-agent:newrelic.ndk using default value: 1.0.3
:newrelic-react-native-agent package.json found at /Users/hillary.snyder/Documents/Projects/movespring/ms-mobile/node_modules/newrelic-react-native-agent/package.json
:newrelic-react-native-agent:version set from package.json: 1.3.2 (1,3,2 - 1003002)
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':newrelic-react-native-agent'.
> compileSdkVersion is not specified. Please add it to build.gradle
``` 

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Output of `npx react-native info`
```
    OS: macOS 13.5.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 53.45 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
    Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.13 => 0.71.13
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
* ex: Which platform is the issue happening on? (Android, iOS, tvOS, etc.)
```
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
```

**Comment by HilSny** [comment]
I can also see compileSdkVersion was removed in this commit from last week: https://github.com/newrelic/newrelic-react-native-agent/commit/c9630db747a9a942a120f95430c4887dccfbd402

**Comment by ndesai-newrelic** [comment]
@HilSny which version of android gradle  plugin are you using? I will add it for next release.

**Comment by HilSny** [comment]
@ndesai-newrelic 
`classpath("com.android.tools.build:gradle:7.4.2")`

Android doesn't build with this at all because to my understanding its a requirement to have this field included. Do you know why it was removed?

We vetting new relic as a potential provider for us but right now we can't test.

**Comment by ndesai-newrelic** [comment]
i will do a hotfix release to fix this issue, can you manually add it to our gradle file for your testing?

**Comment by HilSny** [comment]
For sure! Thank you so much for your super quick response :)

**Comment by AkhtarZaman7** [comment]
Adding manually to build.gradle works fine

`/node_modules/newrelic-react-native-agent/android/build.gradle`

```
 defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
        compileSdkVersion 33
        versionCode 1
        versionName version
    }
```

Add    **compileSdkVersion 33**
Also for me I had to change my project's minSdk to 24 and it works fine

**Comment by ndesai-newrelic** [comment]
@HilSny @AkhtarZaman7 can you check it in our latest release? it is fixed now.

**Comment by LFMAKER** [comment]
@ndesai-newrelic same in 1.3.2

**Comment by ndesai-newrelic** [comment]
@LFMAKER it is already released yesterday.
