### ISSUE TITLE
EAS Build Fails for Android due to minSdk

### ISSUE THREAD

**Issue by ws998116** [newrelic/newrelic-react-native-agent#138]
## Description

Building my project with EAS and `newrelic-react-native-agent v1.3.3` using the expo plugin `newrelic-react-native-agent` fails for Android due to the minSdk setting.

## Steps to Reproduce

Follow the steps to [install New Relic in an Expo app](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/) and attempt to build Android with EAS.

## Relevant Logs / Console output

```
/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.newrelic.agent.android:agent-ndk:1.0.3] /home/expo/.gradle/caches/transforms-3/05998bc95bfbaf2d22099527a60daa99/transformed/jetified-agent-ndk-1.0.3/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.newrelic.agent.android.ndk" to force usage (may lead to runtime failures)
```

## Additional context

A fix is available by using the `expo-build-properties` plugin.

**Comment by objectiveSee** [comment]
In the meantime, here's the fix using `expo-build-properties`:
# app.json
```
        "expo-build-properties",
        {
          "android": {
            "minSdkVersion": 24
          }
        }
      ],
      
```
