### ISSUE TITLE
NRMModularAgent Error Compiling iOS

### ISSUE THREAD

**Issue by dennishernandezdriscolls** [newrelic/newrelic-react-native-agent#141]
I'm getting these errors when I'm building my react native project and using newrelic-react-native-agent 1.3.3 and 1.3.4, could you help me? 

[RUN_FASTLANE]
❌  (node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:302:65)

  300 | }
  301 |
> 302 | RCT_EXPORT_METHOD(addHTTPHeadersTrackingFor:(NSArray<NSString*> _Nonnull) headers) {
      |                                                                 ^ nullability specifier '_Nonnull' cannot be applied to non-pointer type 'NSArray<NSString *>'
  303 |     // todo: Not sure if we need to check the validity of these arguments at all..
  304 |     [NewRelic addHTTPHeadersTrackingFor:headers];
  305 | }

[RUN_FASTLANE]
❌  (node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:302:75)

  300 | }
  301 |
> 302 | RCT_EXPORT_METHOD(addHTTPHeadersTrackingFor:(NSArray<NSString*> _Nonnull) headers) {
      |                                                                           ^ interface type 'NSArray<NSString *>' cannot be passed by value; did you forget * in 'NSArray<NSString *>'?
  303 |     // todo: Not sure if we need to check the validity of these arguments at all..
  304 |     [NewRelic addHTTPHeadersTrackingFor:headers];
  305 | }

[RUN_FASTLANE]
❌  (node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:370:1)

  368 | }
  369 |
> 370 | RCT_EXPORT_METHOD(addHTTPHeadersTrackingFor:(NSArray<NSString*>*_Nonnull) headers) {
      | ^ duplicate declaration of method 'addHTTPHeadersTrackingFor:'
  371 |     [NewRelic addHTTPHeaderTrackingFor:headers];
  372 | }
  373 |

[RUN_FASTLANE]
❌  (node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:304:15)

  302 | RCT_EXPORT_METHOD(addHTTPHeadersTrackingFor:(NSArray<NSString*> _Nonnull) headers) {
  303 |     // todo: Not sure if we need to check the validity of these arguments at all..
> 304 |     [NewRelic addHTTPHeadersTrackingFor:headers];
      |               ^ no known class method for selector 'addHTTPHeadersTrackingFor:'
  305 | }
  306 |
  307 | /**

**Comment by ndesai-newrelic** [comment]
@dennishernandezdriscolls i will check it from our side

**Comment by arelstone** [comment]
We are experiencing the same after bumping to v1.3.4

/............/Mobile-React-Native/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:302:65 Nullability specifier '_Nonnull' cannot be applied to non-pointer type 'NSArray<NSString *>'

/............/Mobile-React-Native/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:302:75 Interface type 'NSArray<NSString *>' cannot be passed by value; did you forget * in 'NSArray<NSString *>'?

/............/Mobile-React-Native/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:304:15 No known class method for selector 'addHTTPHeadersTrackingFor:'

/............/Mobile-React-Native/node_modules/newrelic-react-native-agent/ios/bridge/NRMModularAgent.m:370:1 Duplicate declaration of method 'addHTTPHeadersTrackingFor:'

**Comment by borgespro** [comment]
Same issue here.

**Comment by ndesai-newrelic** [comment]
@borgespro @arelstone @dennishernandezdriscolls can you check in latest version?

**Comment by dennishernandezdriscolls** [comment]
In my case the issue was fixed with the version  "newrelic-react-native-agent": "^1.3.5"

**Comment by arelstone** [comment]
same. 1.3.5 works for us 👏
