### ISSUE TITLE
New relic integration breaks apk signature

### ISSUE THREAD

**Issue by freeboub** [newrelic/newrelic-react-native-agent#144]
## Description

While integrating the new relic package we get an invalid signature error.

## Steps to Reproduce

Build the app with new relic integration
new relic integration implies adding following line in gradle file:
classpath "com.newrelic.agent.android:agent-gradle-plugin:6.2.0"
after agent-gradle-plugin integration we have following signature report:

% apksigner verify --verbose ~/Downloads/app.apk
Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v3.1 scheme (APK Signature Scheme v3.1): false
Verified using v4 scheme (APK Signature Scheme v4): false

## Expected Behavior

before agent-gradle-plugin integration we have following signature report:

% apksigner verify --verbose ~/Downloads/app.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v3.1 scheme (APK Signature Scheme v3.1): false
Verified using v4 scheme (APK Signature Scheme v4): false

## Relevant Logs / Console output

Not needed I guess as it is a signing issue.

## Your Environment

Issue happened in react native environment. I also try to upgrade to 
classpath "com.newrelic.agent.android:agent-gradle-plugin:7.0.0"
Without any success

## Additional context

This signature V1 is necessary to be able to embed the app in a firmware image.
Without it, the app will not be presented in to the user.

Do you know if this signature rework is expected / necessary or if this is just an unexpected side effect

**Comment by ndesai-newrelic** [comment]
closed this as we got internal ticket for this.

**Comment by freeboub** [comment]
You are right, thank you for the support!
The solution was to force enableV1Signing in gradle

https://developer.android.com/reference/tools/gradle-api/7.4/com/android/build/api/variant/SigningConfig#enableV1Signing()
