### ISSUE TITLE
Instrumentation of Android Dynamic feature modules is not supported in this version

### ISSUE THREAD

**Issue by mis8680** [newrelic/newrelic-react-native-agent#147]
## Description

I am experiencing an issue with the New Relic Android agent where it fails to instrument Android Dynamic Feature Modules.

## Steps to Reproduce

1. Integrate the New Relic Android agent as per [the documentation. ](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/)
2. Build the Android app (react-native run-android)

## Expected Behavior

The Android build should be successful.

## Relevant Logs / Console output

```
FAILURE: Build failed with an exception.

* Where:
Build file '/REACT_NATIVE_PROJECT_FOLDER/android/app/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'newrelic']
> Failed to apply plugin 'newrelic'.
   > Instrumentation of Android Dynamic feature modules is not supported in this version.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.
```

## Your Environment

* React Native version: 0.64.2
* New Relic react native agent version: 1.3.5 (https://github.com/newrelic/newrelic-react-native-agent?tab=readme-ov-file)
* `classpath "com.newrelic.agent.android:agent-gradle-plugin:7.2.0"`
* Android Studio version: Android Studio Hedgehog | 2023.1.1 Patch 2
* Gradle version: 6.5. ~ 7.3.3 (tried multiple versions)
* Platform: Android

## Additional context

I tried a few things that I found from the newrelic forum but they didn't help.

**Comment by ndesai-newrelic** [comment]
@mis8680 we are working on this.

**Comment by ndesai-newrelic** [comment]
@mis8680 we added support for dynamic feature, please let us know it is working for react native or not.
