### ISSUE TITLE
crashes on iOS 13 and iOS 14, and the crash occurs at -[NSURLResponse allHeaderFields]: unrecognized selector

### ISSUE THREAD

**Issue by renyufei8023** [newrelic/newrelic-react-native-agent#149]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
crashes on iOS 13 and iOS 14, and the crash occurs at -[NSURLResponse allHeaderFields]: unrecognized selector, newrelic-react-native-agent version is 1.3.5,NewRelicAgent version is 7.4.8,Xcode version is 14.2
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
Crash when starting the app with default configuration

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )

## Your Environment
 newrelic-react-native-agent version is 1.3.5,NewRelicAgent version is 7.4.8,Xcode version is 14.2

**Comment by renyufei8023** [comment]
<img width="1621" alt="截屏2024-02-20 09 15 47" src="https://github.com/newrelic/newrelic-react-native-agent/assets/8408209/e1008f03-0fd4-42cd-a666-a21ac5f373e9">

**Comment by ndesai-newrelic** [comment]
@renyufei8023 are you using any other performance monitor tool?

**Comment by cristianrdu** [comment]
any update regarding this?

**Comment by ndesai-newrelic** [comment]
@cristianrdu can you share crash report and sample app for this?

**Comment by ndesai-newrelic** [comment]
@renyufei8023 can you also share crash report and sample app for this?

**Comment by cristianrdu** [comment]
<img width="1071" alt="Screenshot 2024-03-07 at 11 53 43" src="https://github.com/newrelic/newrelic-react-native-agent/assets/34180169/3a29ff84-3663-4f61-8b08-f6eabfe4b3cc">
<img width="649" alt="Screenshot 2024-03-07 at 11 53 54" src="https://github.com/newrelic/newrelic-react-native-agent/assets/34180169/6d9138f9-ebe2-4cc4-978b-2d23ccd07556">


This crash happens ONLY if `interactionTracingEnabled` is set to enabled in the agent configurations apparently...

The error msg I get when I run the Xcode debugger is similar to this thread too: https://forum.newrelic.com/s/hubtopic/aAX8W000000PHdnWAG/bug-to-compile-app

**Comment by ndesai-newrelic** [comment]
@cristianrdu @renyufei8023 we identified issue on our side, it will fix it on our next react native agent release.

**Comment by cristianrdu** [comment]
Great to hear 😀. do you know when the next release will be?

**Comment by ndesai-newrelic** [comment]
@cristianrdu @renyufei8023 fixed in latest release.
