### ISSUE TITLE
Invalid privacy manifest

### ISSUE THREAD

**Issue by ducbinh1995** [newrelic/newrelic-react-native-agent#153]
I just submitted my app for Apple review, and I got the following back.

> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file
> from the following path is invalid:
> “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. While no action is
> required at this time, starting May 1, 2024, when you upload a new app or
> app update, keys and values in your app’s privacy manifest must be in a
> valid format. For more details about privacy manifest files, visit:
> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the  file
> references one or more APIs that require reasons, including the following
> API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action
> is required at this time, starting May 1, 2024, when you upload a new app
> or app update, you must include a NSPrivacyAccessedAPITypes array in your
> app’s privacy manifest to provide approved reasons for these APIs used by
> your app’s code. For more details about this policy, including a list of
> required reason APIs and approved reasons for usage, visit:
> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the  file
> references one or more APIs that require reasons, including the following
> API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is
> required at this time, starting May 1, 2024, when you upload a new app or
> app update, you must include a NSPrivacyAccessedAPITypes array in your
> app’s privacy manifest to provide approved reasons for these APIs used by
> your app’s code. For more details about this policy, including a list of
> required reason APIs and approved reasons for usage, visit:
> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the  file
> references one or more APIs that require reasons, including the following
> API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action
> is required at this time, starting May 1, 2024, when you upload a new app
> or app update, you must include a NSPrivacyAccessedAPITypes array in your
> app’s privacy manifest to provide approved reasons for these APIs used by
> your app’s code. For more details about this policy, including a list of
> required reason APIs and approved reasons for usage, visit:
> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the  file
> references one or more APIs that require reasons, including the following
> API categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action
> is required at this time, starting May 1, 2024, when you upload a new app
> or app update, you must include a NSPrivacyAccessedAPITypes array in your
> app’s privacy manifest to provide approved reasons for these APIs used by
> your app’s code. For more details about this policy, including a list of
> required reason APIs and approved reasons for usage, visit:
> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> Apple Developer Relations
> 
> Contact Us https://developer.apple.com/contact/ | App Store Connect
> https://appstoreconnect.apple.com/ | One Apple Park Way, Cupertino, CA
> 95014
> Privacy Policy https://www.apple.com/legal/privacy/ | Terms of Service
> https://www.apple.com/legal/internet-services/itunes/
> 
> Contact Us https://developer.apple.com/contact/ | App Store Connect
> https://appstoreconnect.apple.com/
> One Apple Park Way, Cupertino, CA 95014
> 
> Privacy Policy https://www.apple.com/legal/privacy/ | Terms of Service
> https://www.apple.com/legal/internet-services/itunes/

How can I fix it?

**Comment by ndesai-newrelic** [comment]
@ducbinh1995 which version of react native agent are you using?

**Comment by ducbinh1995** [comment]
> @ducbinh1995 which version of react native agent are you using?

I'm using 1.3.5

**Comment by ndesai-newrelic** [comment]
@ducbinh1995 we will fix this issue in our future release.

**Comment by ducbinh1995** [comment]
> @ducbinh1995 we will fix this issue in our future release.

Thanks.

**Comment by mbruin-NR** [comment]
@ducbinh1995  We added a privacy manifest to the iOS agent in version 7.4.7. If you are still seeing this issue can you double check that you are using the most recent version of the iOS agent? 
We are not able to reproduce a warning from submitting our test apps to the app store. Can you send us an example app that can reproduce it?

**Comment by ducbinh1995** [comment]
Hi.
I have re-install the library and the problem had resolved. Thanks!

**Comment by griarman** [comment]
I'm sill getting the issue, after updating to the last version `1.3.7`
