### ISSUE TITLE
Android not getting any logs/events

### ISSUE THREAD

**Issue by burakkgunduzz** [newrelic/newrelic-react-native-agent#155]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

I have installed newrelic for react native. My ios app is getting http requests, other logs etc but android app does not get anything. 0 logs. 

By the way, I did not apply "(Android-native apps only) Install the Android agent" step (that includes some adjustments in build.gradle etc.) in the documentation since this is a react-native app. Is it necessary to apply that step because it is a little bit confusing and not clear from the title of the step?

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
npm i newrelic-react-native-agent
my react-native index.js is below 
```js
import { AppRegistry, Platform } from 'react-native'
import NewRelic from 'newrelic-react-native-agent'
import Config from 'react-native-config'
import { version } from '../package.json'
import App from './app/App'

let appToken
if (Platform.OS === 'ios') {
  appToken = Config.NEWRELIC_IOS_TOKEN
} else {
  appToken = Config.NEWRELIC_ANDROID_TOKEN
}

const agentConfiguration = {
  //Android Specific
  // Optional:Enable or disable collection of event data.
  analyticsEventEnabled: true,
  // Optional:Enable or disable crash reporting.
  crashReportingEnabled: true,
  // Optional:Enable or disable interaction tracing. Trace instrumentation still occurs, but no traces are harvested. This will disable default and custom interactions.
  interactionTracingEnabled: true,
  // Optional:Enable or disable reporting successful HTTP requests to the MobileRequest event type.
  networkRequestEnabled: true,
  // Optional:Enable or disable reporting network and HTTP request errors to the MobileRequestError event type.
  networkErrorRequestEnabled: true,
  // Optional:Enable or disable capture of HTTP response bodies for HTTP error traces, and MobileRequestError events.
  httpRequestBodyCaptureEnabled: true,
  // Optional:Enable or disable agent logging.
  loggingEnabled: true,
  // Optional:Specifies the log level. Omit this field for the default log level.
  // Options include: ERROR (least verbose), WARNING, INFO, VERBOSE, AUDIT (most verbose).
  logLevel: NewRelic.LogLevel.INFO,
  // iOS Specific
  // Optional:Enable/Disable automatic instrumentation of WebViews
  webViewInstrumentation: true
  // Optional:Set a specific collector address for sending data. Omit this field for default address.
  // collectorAddress: "",
  // Optional:Set a specific crash collector address for sending crashes. Omit this field for default address.
  // crashCollectorAddress: "",
  // Optional:Enable or disable reporting data using different endpoints for US government clients
  // fedRampEnabled: false
  // Optional: Enable or disable offline data storage when no internet connection is available.
  // offlineStorageEnabled:true
}
if (!__DEV__) {
  NewRelic.startAgent(appToken, agentConfiguration)
  NewRelic.setJSAppVersion(version)
}
AppRegistry.registerComponent('myAppName', () => App)

```
## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
it should work on both android and ios. The config is same, it works on ios but not on android.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )
I see in my terminal 
LOG  [NRMA] React Native agent started.
 LOG  [NRMA] New Relic React Native agent version 1.3.7

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
* it is happening in android. I tried both development and release env. Not working in both.

**Comment by burakkgunduzz** [comment]
yes, it seems i also need to follow android step. Since the problem is solved, i am closing this issue.

**Comment by jbdoster** [comment]
What was the solution for this? Why wasn't it posted?
