### ISSUE TITLE
Upgrade @expo/config-plugins to solve project configuration errors with Expo 50

### ISSUE THREAD

**Issue by ws998116** [newrelic/newrelic-react-native-agent#156]
## Description

My app fails to build when I include this library and plugin with Expo 50

## Steps to Reproduce

Follow the installation steps in this project and attempt to build with EAS. (Also see expo-doctor output)

## Expected Behavior

Project builds successfully

## Relevant Logs / Console output

`npx expo-doctor@latest` error output:
```
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.8.0

Found invalid:

  @expo/config-plugins@7.2.5
```

## Your Environment

Attempting to build Android app with a medium EAS worker. Connection to worker fails after ~15 minutes.

**Comment by ndesai-newrelic** [comment]
@ws998116 created internal ticket to work on this.
