### ISSUE TITLE
ANR com.newrelic.agent.android.ndk.ANRMonitor.anrMonitorRunner$lambda-1 #198

### ISSUE THREAD

**Issue by sean5940** [newrelic/newrelic-react-native-agent#158]
There is a high frequency of ANR (Application Not Responding) issues being reported in the Android app currently deployed. Interestingly, these issues are only reported to occur on Android 13.

[information]
OS: Android 13
newrelic-react-native-agent: 1.3.7,

[attachment]
[stacktrace.txt](https://github.com/newrelic/newrelic-android-agent/files/14986415/stacktrace.txt)

**Comment by ndesai-newrelic** [comment]
@SungilJung https://github.com/firebase/firebase-android-sdk/issues/4831 it looks like same issue, can you share example app where the issue is reproducible?

**Comment by SungilJung** [comment]
@ndesai-newrelic The problem happens sporadically, so it's not possible to provide an app that consistently reproduces the issue. However, according to the data logged in Firebase, this issue occurs when the app is launched via Firebase FCM notifications while the app is not running.

**Comment by ndesai-newrelic** [comment]
@sean5940 is it still the issue?
