### ISSUE TITLE
Upgrade @expo/config-plugins for Expo 51

### ISSUE THREAD

**Issue by StaffLyft** [newrelic/newrelic-react-native-agent#172]
## Description

My app fails to build when I include this library and plugin with Expo 51

## Steps to Reproduce

Follow the installation steps in this project and attempt to build with EAS. (Also see expo-doctor output)

## Expected Behavior

Project builds successfully

## Relevant Logs / Console output

npx expo-doctor@latest error output:

`Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.9.2
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.`

## Your Environment

Attempting to build Android app with a medium EAS worker. Connection to worker fails after ~15 minutes.

**Comment by ndesai-newrelic** [comment]
@StaffLyft we will update the package for next release.

**Comment by jake-carpenter** [comment]
Thank you for the quick turnaround on this @ndesai-newrelic
