### ISSUE TITLE
use of undeclared identifier 'NRFeatureFlag_BackgroundReporting';

### ISSUE THREAD

**Issue by pnodet** [newrelic/newrelic-react-native-agent#177]
## Description

<img width="1244" alt="Screenshot 2024-07-19 at 09 08 15" src="https://github.com/user-attachments/assets/d334f1d9-7b1e-4b84-a405-e05132610edc">

## Relevant Logs / Console output

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.

## Your Environment

"newrelic-react-native-agent": "^1.3.9"

❯ npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 74.33 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.local/state/fnm_multishells/41778_1721335464201/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.local/state/fnm_multishells/41778_1721335464201/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: ^0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by ndesai-newrelic** [comment]
@pnodet can you reinstall your Pod for iOS?

**Comment by pnodet** [comment]
Indeed issue seems to be resolved, mb sry
