### ISSUE TITLE
Call console.error when client call console.debug

### ISSUE THREAD

**Issue by whalemare** [newrelic/newrelic-react-native-agent#182]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

When in client code developer call `console.debug`, NewRelic with monkey patching proxy this call to `console.error` 

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

https://github.com/newrelic/newrelic-react-native-agent/blob/7f79b2b009a1973deb74438e0fe52b70854de83e/index.js#L656-L659

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

Call will be proxied to console.debug

```js
console.debug.apply(console, arguments);
```

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )

no applicable

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Output of `npx react-native info`
* ex: Which platform is the issue happening on? (Android, iOS, tvOS, etc.)
* ex: Any conflicting packages installed?

no applicable

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

ex: If appropriate and possible, it would be helpful to add [Charles traces](https://forum.newrelic.com/s/hubtopic/aAX8W0000008bQlWAI/relic-solution-setting-up-and-collecting-charles-trace-for-android-apps).

no applicable

**Comment by arelstone** [comment]
I am experiencing this issue too.. Also after upgrading to version 1.4.1

**Comment by ndesai-newrelic** [comment]
@arelstone we are aware about this issue, we will fix it in next release.

**Comment by ndesai-newrelic** [comment]
@arelstone it is fixed in 1.4.3
