### ISSUE TITLE
iOS SIGSEGV (Segmentation fault) Crash

### ISSUE THREAD

**Issue by gailegurskytedbg** [newrelic/newrelic-react-native-agent#186]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Not able to reproduce it locally, but significant amount of crashes are appearing on new relic.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

libobjc.A.dylib
objc_retain_x0 (libobjc.A.dylib)
NewRelic
0x104e40000 + 465560
NewRelic
0x104e40000 + 463344
NewRelic
0x104e40000 + 263884
FBSDKCoreKit_Basics
FBSDKURLSessionTask.m line 30 in -[FBSDKURLSessionTask initWithRequest:fromSession:completionHandler:] (FBSDKURLSessionTask.m:30)
FBSDKCoreKit_Basics
FBSDKURLSession.m line 31 in __55-[FBSDKURLSession executeURLRequest:completionHandler:]_block_invoke (FBSDKURLSession.m:31)
FBSDKCoreKit_Basics
FBSDKURLSession.m line 48 in -[FBSDKURLSession updateSessionWithBlock:] (FBSDKURLSession.m:48)
FBSDKCoreKit_Basics
FBSDKURLSession.m line 34 in -[FBSDKURLSession executeURLRequest:completionHandler:] (FBSDKURLSession.m:34)
FBSDKCoreKit
FBSDKGraphRequestConnection.m line 399 in -[FBSDKGraphRequestConnection start] (FBSDKGraphRequestConnection.m:399)
FBSDKCoreKit
FBSDKServerConfigurationManager.m line 186 in -[FBSDKServerConfigurationManager loadServerConfigurationWithCompletionBlock:] (FBSDKServerConfigurationManager.m:186)
FBSDKCoreKit
FBSDKServerConfigurationManager.m line 122 in -[FBSDKServerConfigurationManager cachedServerConfiguration] (FBSDKServerConfigurationManager.m:122)
FBSDKCoreKit
FBSDKGraphRequestPiggybackManager.m line 164 in -[FBSDKGraphRequestPiggybackManager addServerConfigurationPiggyback:] (FBSDKGraphRequestPiggybackManager.m:164)
FBSDKCoreKit
-[FBSDKGraphRequestPiggybackManager addPiggybackRequests:] (FBSDKGraphRequestPiggybackManager.m:0)
FBSDKCoreKit
FBSDKGraphRequestConnection.m line 376 in -[FBSDKGraphRequestConnection start] (FBSDKGraphRequestConnection.m:376)
FBSDKCoreKit
FBSDKAppEventsConfigurationManager.m line 109 in -[FBSDKAppEventsConfigurationManager loadAppEventsConfigurationWithBlock:] (FBSDKAppEventsConfigurationManager.m:109)
FBSDKCoreKit
FBSDKAppEvents.m line 929 in -[FBSDKAppEvents fetchServerConfiguration:] (FBSDKAppEvents.m:929)
FBSDKCoreKit
FBSDKAppEvents.m line 1269 in -[FBSDKAppEvents flushOnMainQueue:forReason:] (FBSDKAppEvents.m:1269)
libdispatch.dylib
_dispatch_call_block_and_release (libdispatch.dylib)
libdispatch.dylib
_dispatch_client_callout (libdispatch.dylib)

OTHER CRASH STACK TRACE

NewRelic
0x106fcc000 + 465560
NewRelic
0x106fcc000 + 463344
NewRelic
0x106fcc000 + 261764
X
RCTHTTPRequestHandler.mm line 103 in -[RCTHTTPRequestHandler sendRequest:withDelegate:] (RCTHTTPRequestHandler.mm:103)
X
RCTNetworkTask.mm line 75 in -[RCTNetworkTask start] (RCTNetworkTask.mm:75)
X
RCTNetworking.mm line 653 in -[RCTNetworking sendRequest:responseType:incrementalUpdates:responseSender:] (RCTNetworking.mm:653)
X
RCTNetworking.mm line 725 in __38-[RCTNetworking sendRequest:callback:]_block_invoke (RCTNetworking.mm:725)
libdispatch.dylib
0x1a745a000 + 9072
libdispatch.dylib
0x1a745a000 + 16592
libdispatch.dylib
0x1a745a000 + 46808
libdispatch.dylib
0x1a745a000 + 49632
libdispatch.dylib
0x1a745a000 + 94808
## Your Environment

React Native Version
0.72.14
ReactNativeAgentVersion
1.3.8
newRelicVersion
7.4.12

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

ex: If appropriate and possible, it would be helpful to add [Charles traces](https://forum.newrelic.com/s/hubtopic/aAX8W0000008bQlWAI/relic-solution-setting-up-and-collecting-charles-trace-for-android-apps).

**Comment by ndesai-newrelic** [comment]
@gailegurskytedbg are you using Firebase SDK? Please Check this:https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/troubleshoot/firebase-incompatibility/

**Comment by gailegurskytedbg** [comment]
@ndesai-newrelic 
Thank you for quick response!
yes, we are using Firebase.

"Disable **some of the functionality** of our agent. If this is an option that works for you see our [api guide] for more info."


In Api Guide I can not tell  which of the functions we should disable to make it work. 
Maybe you have a configuration example which should work with Firebase, which features should we disable in newrelic? 
Thanks!

**Comment by ssaishankar06854** [comment]
Could please let us know which functions should we disable to make it work with Firebase.  It would also help if you could provide some working example which works for both NewRelic and Firebase.

Would appreciate if you could expedite and provide us your suggestion ASAP.

**Comment by ndesai-newrelic** [comment]
@ssaishankar06854 you can disable interactionTracingEnabled: false. you can also start NewRelic agent from AppDelegate and before you configure firebase agent.

**Comment by ndesai-newrelic** [comment]
@ssaishankar06854 is this still an issue?

**Comment by gailegurskytedbg** [comment]
@ndesai-newrelic 
Thank you for your prompt responses and the initial guidance provided regarding disabling interactionTracingEnabled and configuring on native side before Firebase. While the issue seemed resolved temporarily, after upgrading to version 1.46, the crash has reoccurred despite following the recommended steps.

This ongoing issue is causing significant challenges and hindering progress in our project. We would greatly appreciate it if you could prioritize this and provide a more robust solution or further insights to resolve the problem definitively.

Thank you for your continued support.

**Comment by spsaucier** [comment]
@ndesai-newrelic What's the best way to enable NR in AppDelegate? I don't see it done that way in the example app.
