### ISSUE TITLE
Mutation of agentConfiguration in Development Mode Causes Error with deepFreezeAndThrowOnMutationInDev

### ISSUE THREAD

**Issue by Jojr** [newrelic/newrelic-react-native-agent#187]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I encountered an issue when setting the **customerConfiguration** properties while in development mode. The **deepFreezeAndThrowOnMutationInDev** function from React Native is detecting and handling the mutation of the agentConfiguration object, resulting in console errors.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

1. In a development environment, set the properties of customerConfiguration.

example: 
```
...
type AnyFunction = (...args: any[]) => any
...
this.agentConfiguration = {
      analyticsEventEnabled: Platform.OS === 'android',
      crashReportingEnabled: true,
      interactionTracingEnabled: true,
      networkRequestEnabled: true,
      networkErrorRequestEnabled: true,
      httpRequestBodyCaptureEnabled: true,
      loggingEnabled: true,
      webViewInstrumentation: true,
      offlineStorageEnabled: true,
    }
    this.enableAgentInDev = true
  }


  supressException =
    <Func extends AnyFunction>(fn: Func): ((...args: Parameters<Func>) => ReturnType<Func>) =>
    (...args: Parameters<Func>): ReturnType<Func> => {
      try {
        return fn(...args)
      } catch (error) {
        console.error(error)
      }
    }

  start = supressException(() => {
    if (this.enableAgentInDev) {
      NewRelic.startAgent(this.appKey, this.agentConfiguration)
    }
  })
...
```

2. Run the application.

3. Observe that the deepFreezeAndThrowOnMutationInDev function generates a console error with the message:

> You attempted to set the key 'analyticsEventEnabled' with the value 'false' on an object that is meant to be immutable and has been frozen.

4. The error is repeated for any altered property of the agentConfiguration object.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
The **agentConfiguration** object should be updated with the properties from **customerConfiguration** without causing errors or warnings from **deepFreezeAndThrowOnMutationInDev**. 

The system should handle configuration changes gracefully in development mode, without alerting about immutability violations.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
**deepFreezeAndThrowOnMutationInDev** path: `node_modules/react-native/Libraries/Utilities/deepFreezeAndThrowOnMutationInDev.js`

<img src="https://github.com/user-attachments/assets/832b45e4-0cfc-42ff-bb71-48d518be63ed" alt="Simulator Screenshot - iPhone 15 Pro - 2024-08-13 at 10 27 24" width="300" height="auto">

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )

## Proposed Solution:
To avoid these errors, I modified the code to use the spread operator, which creates a shallow copy of the objects:

From `this.config = Object.assign(this.agentConfiguration, customerConfiguration);`
To `this.config = {...this.agentConfiguration, ...customerConfiguration};`

I would like to understand if there is a specific reason for the current implementation and if there is a recommended approach for handling state immutability in development mode. I am looking for a solution that allows setting agent configuration properties without triggering the **deepFreezeAndThrowOnMutationInDev** function.

## Your Environment
React Native NewRelicAgent: 1.4.1
iOS NewRelicAgent: 7.5.0
Android NewRelicAgent: 7.5.0

React Native: 0.72.9

Thank you for your assistance!

**Comment by duraz0rz** [comment]
Yeah, this is pretty annoying in development mode. `Object.assign` mutates the original object (`this.agentConfiguration`), so this error gets thrown even if you don't change customer configuration.

**Comment by ndesai-newrelic** [comment]
@duraz0rz can you provide sample app for this issue? we are unable to reproduce the issue

**Comment by JohnnyBravoFromTexas** [comment]
@ndesai-newrelic were we able to replicate the above?

**Comment by ndesai-newrelic** [comment]
@duraz0rz is it still an issue? we are unable to reproduce it from our side.

**Comment by ndesai-newrelic** [comment]
@duraz0rz Can you please raise a PR for this issue? I think the code change suggested in the description would be a good solution. I will also look into this from my side also.
