### ISSUE TITLE
High memory consumption and OOM crashes caused by frequent recordError calls

### ISSUE THREAD

**Issue by yuliya9** [newrelic/newrelic-react-native-agent#198]
## Description

We have observed frequent Out Of Memory (OOM) crashes in our app, which we traced back to the recent addition of the recordError function in our codebase. When recordError is invoked frequently, memory consumption increases rapidly, ultimately leading to OOM crashes.

## Steps to Reproduce

1. Call the recordError function repeatedly.
2. Monitor memory usage and observe the rapid increase in memory consumption.

## Expected Behavior

Memory consumption should remain stable and not increase continuously with repeated calls to recordError.

## Your Environment
New Relic React Native Agent version: 1.2.0
React Native version: 0.67.5
Platform: Android

## Additional context
NewRelicAgent configuration:
```
{
  analyticsEventEnabled: true,
  nativeCrashReportingEnabled: true,
  crashReportingEnabled: true,
  interactionTracingEnabled: true,
  networkRequestEnabled: true,
  networkErrorRequestEnabled: true,
  httpResponseBodyCaptureEnabled: true,
  loggingEnabled: true,
  logLevel: NewRelicAgent.LogLevel.INFO,
  webViewInstrumentation: true
}
```

`NewRelicAgent.setMaxEventBufferTime(60)`
`NewRelicAgent.setMaxEventPoolSize(4000)`

**Comment by ndesai-newrelic** [comment]
@yuliya9 we fixed this issue by disabling the event persistence functionality, we will release it soon.

**Comment by ndesai-newrelic** [comment]
@yuliya9 it is fixed now. can you check in latest release?
