### ISSUE TITLE
RecordCustomEvent is not recording in  Android(React-native agent), While IOS is working fine

### ISSUE THREAD

**Issue by KarthikBaleneni** [newrelic/newrelic-react-native-agent#203]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

RecordCustomEvent is  not reflecting in Events Explorer , while in IOS same code is working 

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

New relic agent initialization

  ```
private initializeNewRelic = async () => {
    let appToken;

    if (Platform.OS === 'ios') {
    appToken = '********';
} else {
    appToken = '*******';
}
    const agentConfiguration = {
    //Android Specific
    // Optional:Enable or disable collection of event data.
    analyticsEventEnabled: true,

    // Optional:Enable or disable crash reporting.
    crashReportingEnabled: true,

    // Optional:Enable or disable interaction tracing. Trace instrumentation still occurs, but no traces are harvested. This will disable default and custom interactions.
    interactionTracingEnabled: true,

    // Optional:Enable or disable reporting successful HTTP requests to the MobileRequest event type.
    networkRequestEnabled: true,

    // Optional:Enable or disable reporting network and HTTP request errors to the MobileRequestError event type.
    networkErrorRequestEnabled: true,

    // Optional:Enable or disable capture of HTTP response bodies for HTTP error traces, and MobileRequestError events.
    httpResponseBodyCaptureEnabled: true,

    // Optional:Enable or disable agent logging.
    loggingEnabled: true,

    // Optional:Specifies the log level. Omit this field for the default log level.
    // Options include: ERROR (least verbose), WARNING, INFO, VERBOSE, AUDIT (most verbose).
    logLevel: NewRelic.LogLevel.INFO,

    // iOS Specific
    // Optional:Enable/Disable automatic instrumentation of WebViews
    webViewInstrumentation: true,
    nativeCrashReportingEnabled: false,

    // Optional:Set a specific collector address for sending data. Omit this field for default address.
    // collectorAddress: "",

    // Optional:Set a specific crash collector address for sending crashes. Omit this field for default address.
    // crashCollectorAddress: ""
};
    NewRelic.startAgent(appToken, agentConfiguration);
    NewRelic.setJSAppVersion(DeviceUtils.codeBundleId());
    NewRelic.setAttribute('appVersion', DeviceUtils.codeBundleId());
    NewRelic.setAttribute('applicationName', DeviceInfo.getApplicationName());
    NewRelic.setAttribute('Platform', PlatformUtils.getPlatform());
    DeviceUtils.getDeviceId().then((deviceID: any) =>
    NewRelic.setAttribute('deviceID',deviceID),
  );
  
  ****Android Native changes :****

```
```
  apply plugin: 'com.android.application'
  apply plugin: 'newrelic'
  
  
  dependencies {
       ---
        classpath 'com.newrelic.agent.android:agent-gradle-plugin:7.5.1'
    }
```
    
    
    **Passing Events :**
    
 ```
   reportUserJourney(breakPointId, timeTakenInMs);
   
   ---
     
  const reportUserJourney = (eventName, timeTaken) => {

  const attributes = new Map();
  attributes.set('timeTaken', timeTaken);

  NewRelic.recordCustomEvent('PerformanceMetrics', eventName, attributes);
};
```
    

## Expected Behavior

[NOTE]: # ()

## event logs should be visible in both android and IOS 

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* React native 0.71.18
*  "newrelic-react-native-agent": "^1.4.5",

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

ex: If appropriate and possible, it would be helpful to add [Charles traces](https://forum.newrelic.com/s/hubtopic/aAX8W0000008bQlWAI/relic-solution-setting-up-and-collecting-charles-trace-for-android-apps).

**Comment by ndesai-newrelic** [comment]
@KarthikBaleneni can you share charles traces for this?

**Comment by ndesai-newrelic** [comment]
@KarthikBaleneni all your requests are not configured for SSL Proxy.We need actual it in human readable format.

**Comment by ndesai-newrelic** [comment]
@KarthikBaleneni https://forum.newrelic.com/s/hubtopic/aAX8W0000008bQlWAI/relic-solution-setting-up-and-collecting-charles-trace-for-android-apps

**Comment by ndesai-newrelic** [comment]
@KarthikBaleneni i can see your customEvent in the .chls traces.
<img width="510" alt="Screenshot 2024-10-09 at 8 27 38 AM" src="https://github.com/user-attachments/assets/60a7d143-318c-49e7-8621-8b04fd752103">

**Comment by ndesai-newrelic** [comment]
@KarthikBaleneni we recommend checking Custom Events in NRQL. Specifically, execute a query to retrieve relevant data and identify where these custom events are being generated.
