### ISSUE TITLE
Upgrade @expo/config-plugins to 9.0.0 for Expo 52

### ISSUE THREAD

**Issue by jake-carpenter** [newrelic/newrelic-react-native-agent#207]
Just a heads up that with the drop of [Expo 52](https://expo.dev/changelog/2024/11-12-sdk-52) today, `expo-doctor` is warning that `@expo/config-plugins@8.0.11` is being used and this is configured for ^8.0.6.

## Description

Received this message from running `npx expo-doctor@latest` after upgrading to Expo 52:

```
Expected package @expo/config-plugins@~9.0.0
Found invalid:
  @expo/config-plugins@8.0.11
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.
```

## Steps to Reproduce

1. Create an Expo 52 project
2. Install newrelic-react-native-agent
3. run `npx expo-doctor@latest`

## Expected Behavior

Expo doctor will run successfully and report no issues.

## Relevant Logs / Console output

```
Expected package @expo/config-plugins@~9.0.0
Found invalid:
  @expo/config-plugins@8.0.11
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.
```

## Your Environment

Untested with build yet. Will report back soon.

## Additional context

N/A

**Comment by jamesboonstra** [comment]
I am also having issues with this. My expo-go app auto-updated, so I was forced to upgrade to SDK 52 to use it. But now I get the same errors plus more when I run expo-doctor@latest. I have upgraded the dependencies, and even removed and reinstalled all of my node modules, but I can't resolve this error. `npx expo install --check` does not fix this either.

SDK 52 is also causing all of my builds to fail. I have reverted back to SDK 51, but now there is no way to test using the expo go application.

`Expected package @expo/config-plugins@~9.0.0
Found invalid:
  @expo/config-plugins@8.0.10
  @expo/config-plugins@8.0.8
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~8.0.0
Found invalid:
  @expo/prebuild-config@7.0.9
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.`

**Comment by jake-carpenter** [comment]
@jamesboonstra It's unrelated to the SDK 52 support, but your options are laid out [here](https://expo.dev/go) (use Android, iOS simulators, or migrate to development builds).

**Comment by ndesai-newrelic** [comment]
@jake-carpenter we will fix this issue in our next release.

**Comment by ndesai-newrelic** [comment]
#208

**Comment by ndesai-newrelic** [comment]
we fixed it in latest release/

**Comment by Elusv** [comment]
> ndesai-newrelic

"latest release".. of what? :-)

**Comment by 1-kaiser** [comment]
![image](https://github.com/user-attachments/assets/89c81dfc-8043-4041-a534-395838e176fc)
same error..

**Comment by jcorning99** [comment]
Does this mean we have to wait for Expo 53 to get this fixed?

**Comment by gogupaul123** [comment]
I am also seeing this issue

**Comment by cornejobarraza** [comment]
Just in case, deleting the `node_modules` folder and either the `package-lock.json` or `yarn.lock` file worked for me
