### ISSUE TITLE
react-navigation <=v4 - getActiveRouteName is not defined

### ISSUE THREAD

**Issue by cccolo** [newrelic/newrelic-react-native-agent#37]
I add the code to react-navigation and crash the app, because getActiveRouteName is not defined

` onNavigationStateChange={NewRelic.onNavigationStateChange}`

`"react-navigation": "4.0.10",`

![Captura de pantalla 2022-11-08 a la(s) 14 17 13](https://user-images.githubusercontent.com/11674528/200632220-c141f760-4924-49c3-90d4-0a810f3d059d.png)

**Comment by kthai-nr** [comment]
Hello, thanks for bringing this to our attention. We've put out a PR for this problem: https://github.com/newrelic/newrelic-react-native-agent/pull/38
