### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jeremybarbet** [newrelic/newrelic-react-native-agent#45]
Hey NewRelic team,

Not really an issue, and would love to move this to a discussion if necessary.

Is there any plan for TypeScript support in this repository or will you rely on the community to create the types through [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

Cheers,

**Comment by ndesai-newrelic** [comment]
@jeremybarbet thanks for your feedback ,we will add this in our backlog

**Comment by kthai-nr** [comment]
Hello, appreciate the feedback. We have linked a pull request with typescript support for our `develop` branch and it should be included in our next release. Once it merges it'll automatically close this issue, but feel free to ask any questions.

**Comment by kthai-nr** [comment]
Hello, @jeremybarbet we've pushed out a new release with TypeScript support. Release is available on npm here: https://www.npmjs.com/package/newrelic-react-native-agent/v/1.0.0. I'll be closing this issue, but feel free to re open or ask any questions if you run into any issues.
