### ISSUE TITLE
recordBreadcrumb and recordError results are not visible in New Relic UI

### ISSUE THREAD

**Issue by strewhella** [newrelic/newrelic-react-native-agent#52]
I've followed the docs in setting up the agent and can see some data piped through to the dashboard like HTTP performance and errors and other crashes, but not breadcrumbs or crashes sent manually via `recordError`. I have all the default settings enabled, running the latest agent `0.0.8`, and using Expo 47.0.8.

**Breadcrumbs**
The [docs located here ](https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/crashes/mobile-crash-event-trail/) indicate that there's an "event trail" tab somewhere on the "Crash Analysis" to view these breadcrumbs, but doesn't appear to be there anymore. Any advice on where to find these?

**Error Boundary**
Where should I be able to find the error traces sent via `NewRelic.recordError`? They don't appear under Logs or Errors inbox, or anywhere else that I've found. Here's my implementation:

`error-boundary.tsx`
```
import { Button } from 'native-base';
import React from 'react';
import ReactNativeErrorBoundary from 'react-native-error-boundary';
import { newRelicAgent } from '../shared/new-relic';
import { colors } from '../styles/tailwind-theme';
import { SvgWarning } from '../svg';
import { IconHero } from './icon-hero';

const ErrorOccurred = (props: { error: Error; resetError: Function }) => (
  <>
    <IconHero
      type="error"
      icon={<SvgWarning fill={colors.red[800]} scale={4} />}
      title="An error occurred"
      description="Sorry, something went wrong. We'll look into it."
    />
    <Button
      mt={4}
      bgColor="blue.600"
      width="100%"
      onPress={() => props.resetError()}
      shadow="5"
    >
      RETRY
    </Button>
  </>
);

export interface ErrorBoundaryProps {
  children: React.ReactNode;
}

export const ErrorBoundary = ({ children }: ErrorBoundaryProps) => (
  <ReactNativeErrorBoundary
    onError={error => newRelicAgent.recordError(error)}
    FallbackComponent={ErrorOccurred}
  >
    {children}
  </ReactNativeErrorBoundary>
);
```

`new-relic.ts`
```
import NewRelic from 'newrelic-react-native-agent';
import { Platform } from 'react-native';
import {
  COMMIT,
  NEW_RELIC_APP_TOKEN_ANDROID,
  NEW_RELIC_APP_TOKEN_IOS,
} from '../env';

export const newRelicAgent = NewRelic;

export const startNewRelicAgent = () => {
  let appToken;
  if (Platform.OS === 'ios') {
    appToken = NEW_RELIC_APP_TOKEN_IOS;
  } else {
    appToken = NEW_RELIC_APP_TOKEN_ANDROID;
  }

  const agentConfiguration = {
    //Android Specific
    // Optional:Enable or disable collection of event data.
    analyticsEventEnabled: true,

    // Optional:Enable or disable crash reporting.
    crashReportingEnabled: true,

    // Optional:Enable or disable interaction tracing. Trace instrumentation still occurs, but no traces are harvested. This will disable default and custom interactions.
    interactionTracingEnabled: true,

    // Optional:Enable or disable reporting successful HTTP requests to the MobileRequest event type.
    networkRequestEnabled: true,

    // Optional:Enable or disable reporting network and HTTP request errors to the MobileRequestError event type.
    networkErrorRequestEnabled: true,

    // Optional:Enable or disable capture of HTTP response bodies for HTTP error traces, and MobileRequestError events.
    httpRequestBodyCaptureEnabled: true,

    //Android Specific
    // Optional: Enable or disable agent logging.
    loggingEnabled: true,

    //iOS Specific
    // Optional:Enable/Disable automatic instrumentation of WebViews
    webViewInstrumentation: true,
  };

  newRelicAgent.startAgent(appToken, agentConfiguration);
  newRelicAgent.setJSAppVersion(COMMIT);
};
```

**Comment by kthai-nr** [comment]
Hello, at the moment the way to see errors is by querying them. You should be able to get these queries by running`` SELECT * FROM `JS Errors` `` to see your errors. This documentation can be found in the both the [README](https://github.com/newrelic/newrelic-react-native-agent#how-to-see-jserrorsfatalnon-fatal-in-newrelic-one) and our [docs website](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/#javascript-errors.)

The event trail is for events that are logged to New Relic before an app crash occurs. For example, if there is somewhere in your code that is crash prone, you can create a breadcrumb in that method by calling `NewRelic.recordBreadcrumb("MethodNameBreadcrumb", {"attr1": "blue","attr2": 9,"attr3": true});`. These breadcrumbs can be found prior to an app crash in that `Crash Analysis` page or via the event explorer or by querying `SELECT * FROM MobileBreadcrumb`. 

Let me know if you can't find breadcrumbs or errors in this way.

**Comment by strewhella** [comment]
Thanks for that info. I'm not seeing either of those as option in the data explorer though (`JS Errors` or `MobileBreadcrumb`). This is the list of event types I'm allowed to query:

<img width="187" alt="image" src="https://user-images.githubusercontent.com/8333989/208579587-d79d8b0d-85f7-4fc2-b512-6ff0f00b3366.png">

**Comment by kthai-nr** [comment]
Can you make sure that you have the correct time range? If you can't find it there, try looking in `Query your data` and `Metrics & Events` on the left sidebar (if you don't have these you can add them through `All Capabilities`. This is what it looks like on my end :
<img width="586" alt="Screen Shot 2022-12-20 at 9 13 04 AM" src="https://user-images.githubusercontent.com/105679755/208726256-8f0ad230-8cae-43ea-afa7-fa44031416a4.png">

**Comment by kthai-nr** [comment]
@strewhella Were you able to find your events?

**Comment by kthai-nr** [comment]
Closed due to inactivity. Feel free to post if there are any questions either here or at https://discuss.newrelic.com/c/full-stack-observability/mobile-apm/31
