### ISSUE TITLE
getting issue when upgraded to 1.1.0 

### ISSUE THREAD

**Issue by maheshgiri50** [newrelic/newrelic-react-native-agent#81]
while generating using xocde getting following error 
using **react-native 0.69.7**
**Xcode 13.1.x on macOS 12.6 (Monterey)**

❌  ld: '/Users/[REDACTED]/Library/Developer/Xcode/DerivedData/MccMobileApp-eroliyjakmjnhsgsereaxcwutksb/Build/Intermediates.noindex/ArchiveIntermediates/MccMobileApp/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/NewRelicAgent/NewRelic.framework/NewRelic' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/[REDACTED]/Library/Developer/Xcode/DerivedData/MccMobileApp-eroliyjakmjnhsgsereaxcwutksb/Build/Intermediates.noindex/ArchiveIntermediates/MccMobileApp/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/NewRelicAgent/NewRelic.framework/NewRelic' for architecture arm64

when I checked in Xcode the bitcode is already enabled for newrelic library so not sure why it is giving this error

**Comment by ndesai-newrelic** [comment]
We only support Xcode 14+. With Xcode 14 and later, the App Store no longer accepts bitcode submissions from Xcode 14. (see [new relic iOS agent docs](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/configuration/retrieve-dsyms-bitcode-apps/)) Please disable bitcode for all your targets and use the latest versions
