### ISSUE TITLE
Expo 48 and @expo/config-plugins

### ISSUE THREAD

**Issue by korifey91** [newrelic/newrelic-react-native-agent#82]
With Expo 48 it is  @expo/config-plugins@"~6.0.0"
Current dependency is `@expo/config-plugins@5.0.4` which produce an issue message when run `npx expo-doctor` command in project

**Comment by ndesai-newrelic** [comment]
@korifey91 thanks for this feedback, we will fix this issue in our next release.

**Comment by kthai-nr** [comment]
Hello @korifey91, we pushed out a [new release](https://www.npmjs.com/package/newrelic-react-native-agent/v/1.2.0) with some expo fixes. Let us know if you are still experiencing problems.
