### ISSUE TITLE
[TypeError: Cannot read property 'startAgent' of null]

### ISSUE THREAD

**Issue by c3budiman** [newrelic/newrelic-react-native-agent#93]
![image](https://user-images.githubusercontent.com/1578830/234677825-74826d95-9dbe-4c5f-8894-8d73a40dd2e8.png)
## hello im facing an issue as image shown, step to reproduce :
![image](https://user-images.githubusercontent.com/1578830/234678391-064de325-3945-4633-b40c-e54c12c18a3f.png)
1. register from mobile select android, close and then open again copy token
2. made component for analytic with new relic, as shown on image (1)
3. import it in _layout.tsx (2)
4. because im using expo, i ran this : npx expo prebuild --clean
5. and then check the additional code for rn-agent in build.gradle and app/build.gradle is already there (3) and (4).
6. and when i start the app using android simulator i got this error : [TypeError: Cannot read property 'startAgent' of null]
7. is there something wrong with my step or is it a bug?

**Comment by kthai-nr** [comment]
Hello, are you using Expo Go to launch your app and are you using a bare workflow? If you're using a managed workflow, take a look at the [expo setup instructions](https://github.com/newrelic/newrelic-react-native-agent#expo).

**Comment by c3budiman** [comment]
yes i use a managed workflow, but not using the templates, because i added it on top of working projects.
here is my config :
![image](https://user-images.githubusercontent.com/1578830/234706881-672db010-2f56-433f-8d85-3c823afa38a3.png)

**Comment by c3budiman** [comment]
ah nevermind it was imposibble for expo go to change the native code on the fly, so i need a real device to actually run it aka not on the expo go. okay my bad thank you
